# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "staging"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
spec:
  description: "the git repository for the Staging environment"
  provider: "https://github.com"
  providerKind: 'github'
  providerName: 'github'
  org: "Morgan-Jenkins-X"
  repo: "jx-asm"
  httpCloneURL: "https://github.com/Morgan-Jenkins-X/jx-asm.git"
  url: "https://github.com/Morgan-Jenkins-X/jx-asm.git"
  scheduler:
    kind: Scheduler
    name: "in-repo"
