apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: eks
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "https://50AC0B317DEA23D24C56E825C29919AE.gr7.us-east-2.eks.amazonaws.com"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: secretsManager
  vault: {}
  webhook: lighthouse
