apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        Morgan-Jenkins-X/https://github.com/Morgan-Jenkins-X/jx-asm.git: true
        Morgan-Jenkins-X/jx-asm: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        Morgan-Jenkins-X/https://github.com/Morgan-Jenkins-X/jx-asm.git: merge
        Morgan-Jenkins-X/jx-asm: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - Morgan-Jenkins-X/jx-asm
        - Morgan-Jenkins-X/https://github.com/Morgan-Jenkins-X/jx-asm.git
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - Morgan-Jenkins-X/jx-asm
        - Morgan-Jenkins-X/https://github.com/Morgan-Jenkins-X/jx-asm.git
      target_url: http://lighthouse-jx.50ac0b317dea23d24c56e825c29919ae.gr7.us-east-2.eks.amazonaws.com/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
